export const SET_AUTH = "SET_AUTH";
export const SET_LOGIN = "SET_LOGIN";
export const SET_LOGIN_STATE = "SET_LOGIN_STATE";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_REGISTER = "SET_REGISTER";
export const SET_CHANGEPASSWORD = "SET_CHANGEPASSWORD";
export const SET_REGISTER_RESET = "SET_REGISTER_RESET";
